(

   ./configure --with-qt-moc=/usr/bin --with-qt-libs=/usr/lib --with-qt-includes=/usr/include/qt --prefix=/usr --localstatedir=/var --sysconfdir=/etc &&
   make						&&

   prepare_install				&&

   make install

) > $C_FIFO 2>&1  
