#! /bin/sh
# 
# Source Mage init.d install information
# SMGL-script-version=20030606
# SMGL-START:S:S25
# SMGL-STOP:0 6:K65
#
# Startup script for the cpufreqd daemon. It's been made using the
# skeleton	example file to build /etc/init.d/ scripts.
#		This file should be used to construct scripts for /etc/init.d.
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian GNU/Linux
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
# Version:	@(#)skeleton  1.9.1  08-Apr-2002  miquels@cistron.nl
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/cpufreqd
NAME=cpufreqd
DESC="CPU Frequency daemon"
RUNLEVEL=3

source /etc/init.d/functions

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo "Starting $DESC: $NAME"
        loadproc $DAEMON
	evaluate_retval
	;;
  stop)
	echo "Stopping $DESC: $NAME "
	killproc $DAEMON
	evaluate_retval
	;;
  reload|force-reload)
	echo "Reloading $DESC configuration..."
	reloadproc $DAEMON
	evaluate_retval
  ;;
  status)
	statusproc $DAEMON
  ;;
  restart)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo "Restarting $DESC: $NAME"
	killproc $DAEMON
	sleep 1
        loadproc $DAEMON
	evaluate_retval
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|status|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
