(

    make all                                            &&
  
    prepare_install                                     &&

    mkdir  -p    /usr/share/doc/$SPELL                  &&
    cp  text.ps  /usr/share/doc/$SPELL/$SPELL.ps

) > $C_FIFO 2>&1
