#sedit  "6690s/Screensaver/Screensaver Properties/"  po/es.po    &&

OPTS="$OPTS --with-dpms-ext --with-xinerama-ext --with-xf86vmode-ext     \
            --with-xf86gamma-ext --with-proc-interrupts --with-xshm-ext  \
            --with-xdbe-ext --with-readdisplay --without-gnome           \
            --without-motif                                              \
            $XSCSV_GTK"                                                  &&

default_build
