./configure  --host=${BUILD}                           \
             --prefix=${INSTALL_ROOT}/usr              \
             --infodir=${INSTALL_ROOT}/usr/share/info  \
             --mandir=${INSTALL_ROOT}/usr/share/man    \
             --with-root-prefix=${INSTALL_ROOT}        \
             --enable-elf-shlibs                       \
             ${OPTS}                             &&
make
