( 

  cp  -fv  /usr/share/apps/kicker/pics/kside.png          \
    /usr/share/apps/kicker/pics/kside-dist.png            &&

  cp  -fv  $SOURCE_DIRECTORY/kside-smgl-3.0.png            \
    /usr/share/apps/kicker/pics/                          &&
    
  cp  -fv  /usr/share/apps/kicker/pics/kside-smgl-3.0.png  \
    /usr/share/apps/kicker/pics/kside.png

) > $C_FIFO 2>&1
