#!/bin/bash

PROGRAM=/usr/sbin/exportfs
RUNLEVEL=3
NEEDS="+remote_fs +network +portmap"

. /etc/init.d/smgl_init

[  -e /etc/exports  ]  ||  exit 0

NUMSERVERS=8
MOUNTDOPTS=

start()
{
  echo "Starting NFS services"
  exportfs -r 
  evaluate_retval

  pkill      "^rpc.rquotad$"  &&  sleep  5
  evaluate_retval
  pkill      "^rpc.mountd$"   &&  sleep  5
  evaluate_retval
  pkill  -1  "^nfsd$"         &&  sleep  5
  evaluate_retval
  pkill      "^rpc.statd$"    &&  sleep  5
  evaluate_retval

  ps  -C  portmap  >  /dev/null  ||
  /sbin/portmap
  evaluate_retval
  /usr/sbin/rpc.rquotad
  evaluate_retval
  /usr/sbin/rpc.mountd  $MOUNTDOPTS
  evaluate_retval
  /usr/sbin/rpc.nfsd    $NUMSERVERS
  evaluate_retval
  /usr/sbin/rpc.statd
  evaluate_retval
}

stop()
{
  echo "Stopping NFS services"
  /usr/sbin/exportfs -au
  evaluate_retval
    
  pkill      "^rpc.rquotad$"
  evaluate_retval
  pkill      "^rpc.mountd$"
  evaluate_retval
  pkill  -1  "^nfsd$"
  evaluate_retval
  pkill      "^rpc.statd$"
  evaluate_retval
}

