export PYTHON_LIBS="-lpython2.3"                  &&
./configure  --build=$BUILD                       \
             --prefix=${INSTALL_ROOT}/usr         \
             --sysconfdir=${INSTALL_ROOT}/etc     \
             --localstatedir=${INSTALL_ROOT}/var  \
             $OPTS                                &&
make
