#!/bin/sh

PROGRAM=/usr/bin/tracedaemon
RUNLEVEL=S
NEEDS="+local_fs"

. /etc/init.d/smgl_init
. /etc/sysconfig/tracedaemon

start()
{
	echo "Starting TraceDaemon for ${PROC_INFO_FILE}"
	$PROGRAM ${OPTS} ${LOG_DIR}/${PROC_INFO_FILE} /proc/${PROC_INFO_FILE}
	evaluate_retval
}
