sedit  "s:/usr/local:$INSTALL_ROOT/usr:"  settings.pro  &&
make_single                                             &&
qmake  mythbrowser.pro                                  &&
make                                                    &&
make_normal
