OPTS="$OPTS
  $OPENLDAP_SLAPD $SLAPD_ACI $SLAPD_DNSSRV $SLAPD_MONITOR
  $OPENLDAP_SLURPD
  --with-subdir=$INSTALL_ROOT/usr
  --enable-shared --enable-static
  --enable-dynamic
  --enable-local" &&

default_build
