#!/bin/bash

RUNLEVEL=3
NEEDS="+network"

ifplugdconf=/etc/ifplugd/ifplugd.conf
if [ -e $ifplugdconf ]; then
  . $ifplugdconf
fi

. /etc/init.d/smgl_init

required_executable /usr/sbin/ifplugd

if [ $# -gt 1 ]; then
  INTERFACES="$(builtin echo $@ | sed s/$1//)"
fi

if [ "x$INTERFACES" = "xauto" ]; then
  INTERFACES="`cat /proc/net/dev | awk '{ print $1 }' | egrep '^(eth|wlan)' | cut -d: -f1`"
fi

case $1 in
  start)    for IF in $INTERFACES; do
              echo "Starting ifplugd on interface $IF..."
              A="`eval echo \$\{ARGS_${IF}\}`"
              [ -z $A ] && A="$ARGS"
              /usr/sbin/ifplugd -i $IF $A
              evaluate_retval
            done
            ;;

  stop)     for IF in $INTERFACES; do
              echo "Stopping ifplugd on interface $IF..."
              /usr/sbin/ifplugd -k -i $IF
              evaluate_retval
            done
            ;;

  status)   for IF in $INTERFACES; do
              echo "Status of ifplugd on interface $IF..."
              /usr/sbin/ifplugd -c -i $IF
              evaluate_retval
            done
            ;;

  restart)  $0 stop
            sleep 3
            $0 start
            ;;

  *)      echo "Usage: $0 {start|stop|restart|status}"
          exit 1
          ;;
esac

