(
  sedit 's/include <xmlversion\.h>/include <libxml\/xmlversion\.h>/'  configure  &&
  OPTS="${OPTS} --with-libdc=/usr"  &&
  default_build
  
#  ./configure  --prefix=/usr      \
#               --with-libdc=/usr  \
#	       $OPTS		  &&
#  make                            &&
#  make  install 

) > $C_FIFO 2>&1
