--- Makefile	2002-08-04 16:33:53.000000000 -0700
+++ Makefile.diff	2002-08-04 16:57:35.000000000 -0700
@@ -63,15 +63,19 @@
 $(CONFIGURE):
 	autoconf
 	./configure \
-		--prefix=/ \
-		--exec-prefix=/ \
-		--sbindir=/sbin \
-		--bindir=/usr/sbin \
+		--build=$$BUILD \
+		--prefix=/usr \
+		--exec-prefix=/usr \
+		--sbindir=/bin \
+		--bindir=/sbin \
 		--libdir=/lib \
-		--libexecdir=/usr/lib \
-		--includedir=/usr/include \
-		--mandir=/usr/share/man \
-		--datadir=/usr/share \
+		--libexecdir=/lib \
+		--includedir=/include \
+		--mandir=/share/man \
+		--datadir=/share \
+		--sysconfdir=/etc \
+		--localstatedir=/var \
+		$$OPTS \
 		$$LOCAL_CONFIGURE_OPTIONS
 	touch .census
 
