#!/bin/bash

PROGRAM=/usr/sbin/cvsfsd
RUNLEVEL=3
NEEDS="+remote_fs"

. /etc/init.d/smgl_init

start()
{
  echo -n "Starting cvs virtual filesystem daemon:"
  if [ ! -d /proc/cvsfs ]; then
    echo -n " kernel module"
    /sbin/modprobe cvsfs
  fi
  echo -n " cvsfsd"
  $PROGRAM &
  ps -C cvfsd > /dev/null
  evaluate_retval
}
