#! /bin/sh
# GETTEXT config file
#
# STATUS is whether the option should be enabled by default or not,
#        and has a value of "on" or "off"
# QUESTION is the option label

STATUS=on
QUESTION="Does your system support GNU gettext?"