(
	prepare_install

	[ -d /usr/share/gotmail ] || mkdir /usr/share/gotmail
	cp gotmail.1 /usr/share/gotmail/
	cp sample.gotmailrc /usr/share/gotmail

	cp gotmail /usr/bin/
	cp gotmail.1 /usr/share/man/man1/	

) > $C_FIFO
