#!/bin/bash
#
# I used the same Order as on http://www.kernel.org/
#
# If some release is not available, use a other version as fallback
# 
# The only thing that matters is the String itself, the script parses all
# necessary information from that
#

LATEST_2_4="2.4.19"
LATEST_2_4_PRE="2.4.20-pre4"

LATEST_2_5="2.5.32"
LATEST_2_5_PRE="2.5.32"

LATEST_2_2="2.2.21"
LATEST_2_2_PRE="2.2.22-rc1"

LATEST_2_0="2.0.39"
LATEST_2_0_PRE="2.0.40-rc6"

LATEST_2_4_AC="2.4.19-ac4"
LATEST_2_4_PRE_AC="2.4.20-pre4-ac2"

LATEST_2_5_DJ="2.5.30-dj1"

