#!/bin/bash
#
# This is a simple script to update all of your installed e17 packages
# for Source Mage GNU/Linux <http://www.sourcemage.org/>
#
# (C) 2005 Eric Sandall <eric@sandall.us>
#
# Released under the GNU GPLv2
#
# Usage: e17update
#

#
# We'll use some Sorcery functions to make this easy
#
source  /etc/sorcery/config  &&

message  "${MESSAGE_COLOR}Building list of packages to update..."  \
         "${DEFAULT_COLOR}"                                        &&
for e_spell in `gaze section e`;  do
  if  [[  `installed_version  $e_spell`  ==  "cvs"  ]];  then
    update_spells="$update_spells $e_spell"
  fi
done  &&

cast  -c  $update_spells
