#!/bin/bash

PROGRAM=/bin/false    # To get auto_init functionality
RUNLEVEL=3
PROVIDES=network
NEEDS="+syslog"

. /etc/init.d/smgl_init

test -x /sbin/ifup     || exit 5
test -x /sbin/ifdown   || exit 5
test -x /sbin/ifconfig || exit 5
test -x /sbin/route    || exit 5
test -x /sbin/modprobe || exit 5

netdevdir=/etc/sysconfig/network

# this provides you with the ability to start/stop/check status on 
# one or more cards if you so desire.

if [ $# -le 1 ]; then
    devices="$(ls $netdevdir | grep dev$ | cut -d. -f1)"
else
    devices="$(echo $@ | sed s/$1//)"
fi

start()
{
  for DEVICE in $devices ; do
    [ "$DEVICE" = "lo" ] && continue
    /sbin/ifup $DEVICE
    evaluate_retval
  done
}

stop()
{
  for DEVICE in $devices ; do
    [ "$DEVICE" = "lo" ] && continue
    /sbin/ifdown $DEVICE
    evaluate_retval
  done
}

status()
{
  for DEVICE in $devices ; do
    unset MODE MODULE IP BROADCAST NETMASK GATEWAY

    . $netdevdir/$DEVICE.dev

    if [ -z "$MODE" ] ; then
      echo " There are errors in $netdevdir/$DEVICE.dev"
    else
      if [ "$MODE" = dynamic ]; then
        statusproc dhcpcd
      fi
      ifconfig $DEVICE
    fi
  done
}

restart()
{
  $0 stop
  sleep 1
  $0 start
}

reload() { exit 3; }

usage()
{
  echo "Usage: $0 {start|stop|restart|status} [DEVICE]"
}
