(

  prepare_install  &&
  mkdir  -p  /usr/share/beep/skins    &&
  cp     -R  $SOURCE  /usr/share/beep/skins    &&
  cp     -R  $SOURCE2  /usr/share/beep/skins    &&
  cp     -R  $SOURCE3  /usr/share/beep/skins    &&
  cp     -R  $SOURCE4  /usr/share/beep/skins    &&
  cp     -R  $SOURCE5  /usr/share/beep/skins    &&
  cp     -R  $SOURCE6  /usr/share/beep/skins    &&
  cp     -R  $SOURCE7  /usr/share/beep/skins    &&
  cp     -R  $SOURCE8  /usr/share/beep/skins    &&
  cp     -R  $SOURCE9  /usr/share/beep/skins

) > $C_FIFO 2>&1
