echo  OPTS = $OPTS  &&
echo  MIDI_OPTS = $MIDI_OPTS  &&
echo  HOBBIT_OPTS = $HOBBIT_OPTS  &&
             #--with-static-xm            \
./configure  --prefix=$INSTALL_ROOT/usr  \
             $MIDI_OPTS                  \
             $HOBBIT_OPTS                \
             $GUI_OPTS                   \
             $OPTS                       &&
make
