### had to cook up some pkg-config files for nss and nspr 
if  spell_ok  nss ; then
  export PKG_CONFIG_PATH="/usr/include/nss:/usr/include/nspr" 
fi                                              &&
default_build &&
cd $SOURCE_DIRECTORY                            
