#!/bin/bash

RUNLEVEL=5
PROVIDES=display_manager

. /etc/init.d/smgl_init

case $1 in
 start)
      /usr/bin/slim -d
      ;;
 stop)
      killall /usr/bin/slim
      ;;
 restart)
      $0 stop
      sleep 2
      $0 start
      ;;
 *)
      echo
      "usage:  $0 [start|stop|restart]"
      ;;
esac
