#!/bin/bash

. /etc/sysconfig/omniMapper

PROGRAM=/usr/bin/omniMapper
ARGS="-port $OMNIMAPPER_PORT -config $OMNIMAPPER_CONFIG $OMNIMAPPER_ARGS"
DESC="omniORB Mapper Server daemon"
RUNLEVEL=3
NEEDS="+network"

. /etc/init.d/smgl_init

required_executable $PROGRAM

start()
{
	echo "Starting: $DESC" &&
	( $PROGRAM $ARGS & ) &&
	sleep 1 &&
	pidof $(basename $PROGRAM) > /var/run/$(basename $PROGRAM).pid
}

stop()
{
	if [[ -f /var/run/$(basename $PROGRAM).pid ]] ; then
		echo "Stopping: $DESC with pid $(cat /var/run/`basename $PROGRAM`.pid)" &&
		kill $(cat /var/run/`basename $PROGRAM`.pid) >> /dev/null 2>&1
	else
		echo "$DESC not running..."
	fi
}
