(
  export ACE_ROOT=/usr/src/ACE_wrappers         &&
	cp -rv $SCRIPT_DIRECTORY/Makefile.gperf       \
         $SOURCE_DIRECTORY/apps/gperf/Makefile  &&
  prepare_install                               &&
  $SCRIPT_DIRECTORY/myacemaker auto

) > $C_FIFO 2>&1
