(

  prepare_install &&
  cp -af \
    lowercase \
    mv_lowercase \
    mv_uppercase \
    mv_capitalize \
    mv_spaces2underscore \
    mv_vfatillegal2underscore \
    mv_underscore2hyphen \
    mv_underscore2null \
    htmlrename \
    Trash \
    swap                      /usr/bin/ &&
  cp -f \
    lowercase.1 \
    htmlrename.1 \
    Trash.1 \
    swap.1                    /usr/share/man/man1

) >$C_FIFO 2>&1
