#!/bin/bash
#
# I used the same Order as on http://www.kernel.org/
#
# If some release is not available, use a other version as fallback
# 
# The only thing that matters is the String itself, the script parses all
# necessary information from that
#

LATEST_2_6="2.6.5"
LATEST_2_6_PRE="2.6.5-rc2"

LATEST_2_4="2.4.25"
LATEST_2_4_PRE="2.4.26-pre6"

LATEST_2_2="2.2.26"
LATEST_2_2_PRE="${LATEST_2_2}"

LATEST_2_0="2.0.40"
LATEST_2_0_PRE="2.0.40-rc8"

LATEST_2_4_AC="2.4.22-ac4"
LATEST_2_6_AC="2.6.0-test1-ac3"

LATEST_2_6_MM="2.6.4-mm1"
