./configure --prefix=$INSTALL_ROOT/usr                \
            --datadir=$INSTALL_ROOT/usr/share/$SPELL  \
            --mandir=$INSTALL_ROOT/usr/man            \
            $OPTS                        &&
make
