(

cp /var/lib/sorcery/grimoire/video/bcast/Makefile $SOURCE_DIRECTORY &&
cp /var/lib/sorcery/grimoire/video/bcast/bcast2000.sh $SOURCE_DIRECTORY &&
./configure &&
make &&
make install &&
cp /usr/bcast/bcast2000.sh /usr/bin/.



) > $C_FIFO 2>&1
