#!/bin/bash

DESCRIPTION="ACPI patch"
SHORT="Advanced Configuration and Power Interface"
HELP="Committed to the development of fundamental ACPI (Advanced Configuration and Power Interface) components for Linux. This includes a generic ACPI table parser, AML interpreter, bus and device drivers, policy, user interface, and support tools."
VERSIONS="acpi-20020918-2.4.18
acpi-20020918-2.4.19-ia64-020821
acpi-20020918-2.4.19
acpi-20020918-2.4.20-pre7
acpi-20020918-2.5.36"

if [[ "$1" == "CONFIG" ]]; then
echo "
SOURCE${COUNTER}=${!PATCH}.diff.gz
SOURCE${COUNTER}_URL=\$SOURCEFORGE_URL/acpi/\$SOURCE${COUNTER}" >> $SPELL_CONFIG
fi
