#!/bin/bash

DESCRIPTION="Con Kolivas Patchset"
SHORT="These are patches designed to improve system responsiveness, with emphasis on desktop pcs"
HELP="See http://kernel.kolivas.net

Base (1000_O1_PE_LL_0306231337_2.4.21-ck3) contains the batch O(1) scheduler, preemptible, low latency and .K.'s interactivity patch

Full (2.4.21-ck3) additionally contains:
 CK's autoregulation vm hacks
 Swap prefetching
 Read Latency2
 Variable HZ setting
 Desktop Tuning 1 and 2
 Scheduler Tunables
 Supermount-NG v1.2.7
 XFS file system 1.3.0pre2
 ACPI 20030522
 Nvidia Nforce2 update
 Bootsplash
 Grsec 1.9.9h"

VERSIONS="1000_O1_PE_LL_0306300059_2.4.21-ck3
2.4.21-ck3"

MD5S[0]=88ae6b245065a3bd1599d5b3974438a6
MD5S[1]=5fe3e852bedfe5c7641b0732004d3c24

if [[ "$1" == "CONFIG" ]]; then
echo "
SOURCE${COUNTER}=patch-${!PATCH}.bz2
SOURCE${COUNTER}_URL[0]=http://members.optusnet.com.au/ckolivas/kernel/\$SOURCE${COUNTER}" >> ${SPELL_CONFIG}.DETAILS

source $SCRIPT_DIRECTORY/MD5PATCH
fi
