#!/bin/bash

DESCRIPTION="Con Kolivas Patchset"
SHORT="These are patches designed to improve system responsiveness, with emphasis on desktop pcs"
HELP="See http://kernel.kolivas.net

Contains:
 batch O(1) scheduler, preemptible, low latency
 C.K.'s interactivity patch
 Read Latency2, Variable HZ setting
 Desktop Tuning 1 and 2, Scheduler Tunables
 Supermount-NG
 XFS file system, Bootsplash, Grsec"

VERSIONS="2.4.23-ck1"

MD5S[0]=ddc0d6fc327a6d12afb2c4c837070b51

CUSTOM=ck_custom
CMENU=(\
    "2.4.23-ckbase-0312022106"     "Base ck patch"          "Base ck contains the batch O(1) scheduler, preemptible, low latency and my interactivity patch" \
    "2.4.23-ckbase-rl2-0312021358" "Read Latency 2"         "Read Latency 2" \
    "2.4.23-rl2-rl2dt-0312022027"  "RL2 Desktop Tuning"     "Changes to the default settings for I/O, Hz and scheduler tunables for optimum responsiveness & interactivity." \
    "2.4.23-rl2dt-vhzj64-0312022318" "Variable HZ setting with 64bit jiffies"         "If you change the Hz, use a multiple of 100. There really is no point going above 1000 Hz." \
    "2.4.23-vhzj64-sm1.2.10-0312022322" "Supermount-NG v1.2.10" "Supermount-NG v1.2.10" \
    "2.4.23-sm1.2.10-bs3.0.7-0312022344" "Bootsplash"   "See http://www.bootsplash.org" \
    "2.4.23-bs3.0.7-xfs1.3.1-0312030031" "XFS file system"   "This is possibly safer with preempt disabled. It may have unimportant patch reject with aavm but works ok." \
   )

CMD5=(\
    "4976155c568264afc0b5b3739400dc41" \
    "8018f69b3dbc1e17978e4d9368013020" \
    "2895f109afa4847af70b3b1f8dfe477e" \
    "df82eb06a58755a61cf15e724cc33b92" \
    "521e75840ec2729b71b4108edd4dd626" \
    "5db4cc3f8a8ed12bf9c6c8c425c9f424" \
    "281e2031abe178fa8c3e3efbbfcb2578" \
   )

if [[ "$1" == "CONFIG" ]]; then
  if [[ "${!PATCH}" == "custom" ]]; then
    for CPATCH in $CK_PATCH; do
      echo "
SOURCE${COUNTER}=patch-${CPATCH}.bz2
SOURCE${COUNTER}_URL[0]=http://www.plumlocosoft.com/kernel/patches/2.4/2.4.23/2.4.23-ck1/split-out/\$SOURCE${COUNTER}" >> ${SPELL_CONFIG}.DETAILS
    (ck_md5_custom $(( $COUNTER - 1 )) $CPATCH) >> ${SPELL_CONFIG}.DETAILS
    COUNTER=$(( $COUNTER + 1 ))
    done
    COUNTER=$(( $COUNTER - 1 ))
  else
    echo "
SOURCE${COUNTER}=patch-${!PATCH}.bz2
SOURCE${COUNTER}_URL[0]=http://www.plumlocosoft.com/kernel/patches/2.4/2.4.23/2.4.23-ck1/\$SOURCE${COUNTER}" >> ${SPELL_CONFIG}.DETAILS
    source $SCRIPT_DIRECTORY/MD5PATCH
  fi
fi

ck_md5_custom()
{
  local CMENU_COUNT=${#CMENU[@]}
  local INDEX=0
  while [[ $INDEX -lt $CMENU_COUNT ]]; do
    if [[ "$2" == "${CMENU[$INDEX * 3]}" ]]; then
      echo "MD5[$1]=${CMD5[$INDEX]}
"
    fi
    INDEX=$(( $INDEX + 1 ))
  done
}

ck_checklist()
{
  local CMENU_COUNT=${#CMENU[@]}
  local INDEX=0
  while [[ $INDEX -lt $CMENU_COUNT ]]; do
    echo ${CMENU[$INDEX]}
    echo ${CMENU[$(( $INDEX + 1 ))]}
    echo "OFF"
    echo ${CMENU[$(( $INDEX + 2 ))]}
    INDEX=$(( $INDEX + 3 ))
  done
}

ck_custom()
{
  CK_PATCH=$( $DIALOG --title "$DESCRIPTION"  \
           --item-help                        \
           --separate-output                  \
           --checklist                        \
           "$SHORT" 0 0 0                     \
           $(ck_checklist) )
}
