#!/bin/bash

DESCRIPTION="Extras to Con Kolivas Patch"
SHORT="Additional less tested additions to the Con Kolivas Patch"
HELP="Contains desktop tuning, variable timeslice, lower disk latency and
compressed caching - less tested but good additions to a desktop pc

REQUIRES ck patch
 
http://kernel.kolivas.net"

VERSIONS="ck2_2.4.20"
MD5S[0]=413c405d810ba7ecfd3f68d814f75323

if [[ "$1" == "CONFIG" ]]; then
echo "
SOURCE${COUNTER}=extras_ck2_2.4.20.patch.bz2
SOURCE${COUNTER}_URL=http://members.optusnet.com.au/ckolivas/kernel/\$SOURCE${COUNTER}" >> ${SPELL_CONFIG}.DETAILS

source $SCRIPT_DIRECTORY/MD5PATCH
fi
