#!/bin/bash

DESCRIPTION="grsecurity patch"
SHORT="Provides ACL (Access Control List) and more"
HELP="features:
ACL system features (Access Control List)
Chroot restrictions
Address space modification protection
Auditing features
Randomization features

see http://www.grsecurity.net/ for details

The fix for the recent ptrace vulnerability has been included as well"

VERSIONS="1.9.9g-2.4.20
2.0-pre3-2.4.20"

PUBRINGFILE=grsecurity.gpg

if [[ "$1" == "CONFIG" ]]; then
echo "
SOURCE${COUNTER}=grsecurity-${!PATCH}.patch
SOURCE${COUNTER}_URL=http://www.grsecurity.net/\$SOURCE${COUNTER}" >> ${SPELL_CONFIG}.DETAILS
source $SCRIPT_DIRECTORY/GPGPATCH
fi
