#!/bin/bash

DESCRIPTION="grsecurity patch"
SHORT="Provides ACL (Access Control List)"
HELP="An ACL (Access Control List) system is software that provides fine-grained access control for your computer."
VERSIONS="1.9.9c-2.4.20"

PUBRINGFILE=grsecurity.gpg

if [[ "$1" == "CONFIG" ]]; then
echo "
SOURCE${COUNTER}=grsecurity-${!PATCH}.patch
SOURCE${COUNTER}_URL=http://www.grsecurity.net/\$SOURCE${COUNTER}" >> ${SPELL_CONFIG}.DETAILS
source $SCRIPT_DIRECTORY/GPGPATCH
fi
