#!/bin/bash

DESCRIPTION="security fix for i2c buffer overflow"
SHORT="security fix for i2c buffer overflow"
HELP="Vulnerability Local User buffer overflow kernel privileges

Inadequate input validation for negative numbers caused improper memory allocation.

This affects linux versions equal to and prior to the patches provided in the 2.4.x series of the i2c driver.
"
VERSIONS="2.4.26"

MD5S[0]=f77f865758933a9b58a23f9450aaf337

if [[ "$1" == "CONFIG" ]]; then
echo "
SOURCE${COUNTER}='linux-${!PATCH}-i2c-core.overflow.patch'
SOURCE${COUNTER}_URL='http://smgl.positivism.org/linux-${!PATCH}-i2c-core.overflow.patch'" >> ${SPELL_CONFIG}.DETAILS
source $SCRIPT_DIRECTORY/MD5PATCH
fi
