#!/bin/bash

DESCRIPTION="security fix for IO Permissions (local)"
SHORT="security fix for IO Permissions (local)"
HELP="Vulnerability: CAN-2003-0246

The 'ioperm' system call does not properly restrict privileges, potentially allowing an unprivileged local user access to the I/O ports on the system.

This patch is for 2.4.20
"
VERSIONS="2.4.20"

MD5S[0]=7688fd830a8c26f13c06a58b437b27a2

if [[ "$1" == "CONFIG" ]]; then
echo "
SOURCE${COUNTER}='index.html?m=105364108603938\\&q=raw'
SOURCE${COUNTER}_URL='http://marc.theaimsgroup.com/?m=105364108603938\\&q=raw;FAKE=.tar.bz2'" >> ${SPELL_CONFIG}.DETAILS
source $SCRIPT_DIRECTORY/MD5PATCH
fi
