#!/bin/bash

DESCRIPTION="LIDS patch"
SHORT="Linux Intrusion Detection System"
HELP="features:
*  Protection of files, No one including root can modify the lids-protected files. File can be hidden.
* Protection of process, No one including root can kill the protected process. Process can be hidden.
* Fine-granulate Access Control with ACLs.
* Use and extend capability to control the whole system.
* Security alert from the kernel.
* Port scanner detector in kernel.
* Support LSM framework in kernel 2.5.x
* Process network access restriction
"
VERSIONS="2.2.1pre1-2.6.9
1.2.2-2.4.28"

if [[ "$1" == "CONFIG" ]]; then
MREL=`echo ${!PATCH} | cut -d'-' -f2`
MVER=`echo ${MREL} | cut -d. -f1,2`

# we get the source tarball, put it in $SPOOL and get the patch as SOURCECOUNTER
SRC=lids-${!PATCH}.tar.gz
if [ ! -e $SOURCE_CACHE/$SRC ] ; then 
    wget -P $SOURCE_CACHE http://www.lids.org/download/v${MVER}/${MREL}/$SRC
fi

tar -z -O  --extract --file=$SOURCE_CACHE/$SRC lids-${!PATCH}/lids-${!PATCH}.patch >$SOURCE_CACHE/lids-${!PATCH}.patch

echo "SOURCE${COUNTER}=lids-${!PATCH}.patch
#SOURCE${COUNTER}_URL=http://www.lids.org/download/v${MVER}/${MREL}/\$SOURCE${COUNTER}" >> ${SPELL_CONFIG}.DETAILS
fi
