#!/bin/bash

DESCRIPTION="preemptible kernel patch"
SHORT="This patch enables a preemptible kernel"
HELP="This patch enables a preemptible kernel, which reduces the latency of the kernel.
It allows processes to be preempted even if in kernel mode.

The design used is to allow a task to be preempted anywhere within the kernel, using spinlocks as markers for non-preemptibility regions.
The resulting system response is greatly increased, with measured average latencies under 1ms."
VERSIONS="2.4.21-pre1-1
2.4.20-ac1-1
2.4.20-1
2.4.19-2
2.4.18-5"

MD5S[0]=263b70d6fa247914197a30b216e53ae9
MD5S[1]=b2e1fae874279ab2363ebe1f162a8a57
MD5S[2]=3e15a012961955d313b624a9e24c5233
MD5S[3]=5f5d42bce8da6cacde2e5fc24921f173
MD5S[4]=5960f685403177baf10927fb1dc78c2a

if [[ "$1" == "CONFIG" ]]; then
echo "
SOURCE${COUNTER}=preempt-kernel-rml-${!PATCH}.patch
SOURCE${COUNTER}_URL=\${KERNEL_URL}/pub/linux/kernel/people/rml/preempt-kernel/v2.4/\$SOURCE${COUNTER}" >> ${SPELL_CONFIG}.DETAILS
source $SCRIPT_DIRECTORY/MD5PATCH
fi
