#!/bin/bash
DESCRIPTION="usbdnet"
SHORT="Provides ethernet over USB for PDA-like things"
HELP="Used to establish ethernet to the Sharp Zaurus, see http://www.ruault.com/Zaurus/ethernet-over-usb-howto.html"
VERSIONS="2.4.19-
2.4.18.
2.4.17."
if [[ "$1" == "CONFIG" ]]; then
echo "
SOURCE${COUNTER}=usbdnet-${!PATCH}patch.gz
SOURCE${COUNTER}_URL=http://www.ruault.com/Zaurus/patches/\$SOURCE${COUNTER}" >> $SPELL_CONFIG
fi
