#  patch -p4 < $SPELL_DIRECTORY/mk.diff &&
#  default_build
#  ./configure --prefix=${INSTALL_ROOT}/usr $OPTS &&
  cd src           &&
  cp $SPELL_DIRECTORY/Makefile ./   &&
#  sed -i "s|-g|$CFLAGS|" Makefile &&
#  make IBPP_PATH=/usr/include EXTRA_LIBS=/usr/include/wx/stc
#  make IBPP_PATH=/usr/include EXTRA_LIBS=/usr/lib/libwx_gtk2_stc-2.4.so
  make
