#!/bin/bash

. /etc/sysconfig/watchdog

PROGRAM=/usr/sbin/watchdog
ARGS="$WD_OPTS"
RUNLEVEL=3
NEEDS="+remote_fs"

. /etc/init.d/smgl_init

start()
{
  echo "Starting watchdog..."
  . /etc/sysconfig/devices
  if [ $DEVICES=/dev ]; then
    if ! ([ -e /dev/misc/watchdog] && [ -e /dev/misc/temperature ] ); then
      echo "No watchdog support in the kernel!"
      exit 5
    fi
  else
    [ -e /dev/watchdog ]    || mknod /dev/watchdog    c 10 130
    [ -e /dev/temperature ] || mknod /dev/temperature c 10 131
  fi
  loadproc $PROGRAM $ARGS
}

stop()
{
  echo "Stopping watchdog..."
  if [ -e /var/run/watchdog.pid ]; then
    kill $(cat /var/run/watchdog.pid)
  else
    /bin/false
  fi
  evaluate_retval
}
