#!/bin/bash

PROGRAM=/usr/bin/postmaster
RUNLEVEL=3
NEEDS="+remote_fs"

. /etc/init.d/smgl_init
. /etc/sysconfig/postgresql

start()
{
  echo "Starting postmaster..."
  cd "$DBPATH" &&
  if  [[  -z  "$PORT"  ]];  then
    su "$USER" -c "pg_ctl -D '$DBPATH' -l '$LOGFILE' start"
  else
    su "$USER" -c "pg_ctl -D '$DBPATH' -l '$LOGFILE' start -o \"-i -p '$PORT'\""
  fi
  evaluate_retval
}

stop()
{
  echo "Stopping postmaster..."
  cd "$DBPATH" &&
  su "$USER" -c "pg_ctl -D '$DBPATH' -m fast stop"
  evaluate_retval
}

restart()
{
  stop   &&
  start
}
